[project]
name = "python-task"
version = "0.1.0"
description = "A short script to filter lists"
authors = [
    { name = "Keys", email = "70819367+keys-i@users.noreply.github.com" },
]
license = { text = "LGPLv2.1" }
readme = "../README.md"
requires-python = ">=3.13"
dependencies = ["requests (>=2.32.4,<3.0.0)", "pytest (>=8.4.1,<9.0.0)"]

[tool.poetry]
packages = [{ include = "src", from = "." }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
